version: 2
updates:
  # Go Modules updates
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  # Github Action updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"