# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrumchrono < Formula
  desc "ScrumChrono is a terminal UI to aid Scrum meetings."
  homepage "https://github.com/pedrojreis/ScrumChrono"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.0/ScrumChrono_Darwin_arm64.tar.gz"
      sha256 "ed8c2a07b05bdabab01465ff3b55fe6f785bc898a7c2e4ac78676e5abd9274a4"

      def install
        bin.install "ScrumChrono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.0/ScrumChrono_Darwin_x86_64.tar.gz"
      sha256 "1094431a0fdd31e59a341c07481f920b8dc7806a6c8b02df7c0fbaa6b19c5f1c"

      def install
        bin.install "ScrumChrono"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.0/ScrumChrono_Linux_arm64.tar.gz"
      sha256 "964c62125aac1c9acbe8537f7bf278e5397df380ea7b845f520add6448b903e0"

      def install
        bin.install "ScrumChrono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.0/ScrumChrono_Linux_x86_64.tar.gz"
      sha256 "cf8979414223fabdddddf4b5a35286176860e443e770f8fafcda35e1224dcb3b"

      def install
        bin.install "ScrumChrono"
      end
    end
  end

  test do
    system "ScrumChrono --version"
  end
end
