# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrumchrono < Formula
  desc "ScrumChrono is a terminal UI to aid Scrum meetings."
  homepage "https://github.com/pedrojreis/ScrumChrono"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.0/ScrumChrono_Darwin_arm64.tar.gz"
      sha256 "54a7ee7a06c70cf60c66a26a933ac514b560f1376f30afac7ace082dca7c1930"

      def install
        bin.install "ScrumChrono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.0/ScrumChrono_Darwin_x86_64.tar.gz"
      sha256 "337263136ced3b5a974a5f1218f57450b81854c55cd8bd47bcc9c9f3c78f1fd7"

      def install
        bin.install "ScrumChrono"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.0/ScrumChrono_Linux_arm64.tar.gz"
      sha256 "ce09cd91606373ddd20de6787287cf08cf8d8803d352bc5da99e5e9c1e4ed38a"

      def install
        bin.install "ScrumChrono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.0/ScrumChrono_Linux_x86_64.tar.gz"
      sha256 "5b542fbba4f521b71bfffb0c873173ffafeb5019438e485dc17c1b9a3a1b3f4a"

      def install
        bin.install "ScrumChrono"
      end
    end
  end

  test do
    system "ScrumChrono --version"
  end
end
